name: Core Build

on:
  workflow_call: # Makes this reusable

jobs:
  build:
    name: Restore & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore CleanArchitectureTemplate.sln

      - name: Build solution
        run: dotnet build CleanArchitectureTemplate.sln --no-restore --configuration Release
